// Public config (safe to serve to browser)
window.ATTRAL_PUBLIC = {
  RAZORPAY_KEY_ID: 'rzp_live_RKD5kwFAOZ05UD', // Your actual Razorpay key ID
  FIREBASE_CONFIG: {
    // Generated by Firebase CLI for e-commerce-1d40f project
    apiKey: "AIzaSyCMzmyqQ-WJuYrK0dNsTqljlDsCkmOIXOk",
    authDomain: "e-commerce-1d40f.firebaseapp.com",
    projectId: "e-commerce-1d40f",
    storageBucket: "e-commerce-1d40f.firebasestorage.app",
    messagingSenderId: "972578972293",
    appId: "1:972578972293:web:3aa31f43650c08cdc17fec",
    measurementId: "G-F47FSRF835"
  },
  // Local development API endpoints
  API_BASE_URL: (function(){
    // Allow an explicit override before this file loads
    if (window.ATTRAL_PUBLIC && window.ATTRAL_PUBLIC.__API_BASE_URL_OVERRIDE__) {
      return window.ATTRAL_PUBLIC.__API_BASE_URL_OVERRIDE__;
    }
    // Always point to the PHP host so localhost frontends can still call live APIs
    return 'https://attral.in';
  })(),
  IS_LOCAL_DEV: window.location.hostname === 'localhost',
  // Base URL to construct affiliate links (override in production if needed)
  AFFILIATE_BASE_URL: (function(){
    // Prefer explicit override if set elsewhere before this file
    if (window.ATTRAL_PUBLIC && window.ATTRAL_PUBLIC.__AFFILIATE_BASE_URL_OVERRIDE__) {
      return window.ATTRAL_PUBLIC.__AFFILIATE_BASE_URL_OVERRIDE__;
    }
    // If running locally, default to production domain; otherwise use current origin
    if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
      return 'https://attral.in';
    }
    return window.location.origin;
  })()
};


