// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3LrzkOVi8rBxWHB2IPTK_Xr4aiC9SqI',
    appId: '1:972578972293:web:admin_web_app',
    messagingSenderId: '972578972293',
    projectId: 'e-commerce-1d40f',
    authDomain: 'e-commerce-1d40f.firebaseapp.com',
    storageBucket: 'e-commerce-1d40f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3LrzkOVi8rBxWHB2IPTK_Xr4aiC9SqI',
    appId: '1:972578972293:android:33235b1790439be8c17fec',
    messagingSenderId: '972578972293',
    projectId: 'e-commerce-1d40f',
    storageBucket: 'e-commerce-1d40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChk60XE6eQ_kKZXgcAiPE8LjOHUfgcixo',
    appId: '1:972578972293:ios:737896b22d4d3ce4c17fec',
    messagingSenderId: '972578972293',
    projectId: 'e-commerce-1d40f',
    storageBucket: 'e-commerce-1d40f.firebasestorage.app',
    iosBundleId: 'com.attral.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChk60XE6eQ_kKZXgcAiPE8LjOHUfgcixo',
    appId: '1:972578972293:ios:737896b22d4d3ce4c17fec',
    messagingSenderId: '972578972293',
    projectId: 'e-commerce-1d40f',
    storageBucket: 'e-commerce-1d40f.firebasestorage.app',
    iosBundleId: 'com.attral.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw3LrzkOVi8rBxWHB2IPTK_Xr4aiC9SqI',
    appId: '1:972578972293:web:admin_web_app',
    messagingSenderId: '972578972293',
    projectId: 'e-commerce-1d40f',
    authDomain: 'e-commerce-1d40f.firebaseapp.com',
    storageBucket: 'e-commerce-1d40f.firebasestorage.app',
  );
}
